# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dino' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dino
  pod 'SwiftSocket'
  target 'DinoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DinoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
